spring.application.name=library-management-system

# Run on port 8090
server.port=8090

# SQLite database file (created automatically in project root)
spring.datasource.url=jdbc:sqlite:library.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Show SQL queries in the console (helpful for learning)
logging.level.com.niranjan=DEBUG
logging.level.org.springframework.web=INFO
